import { Node, EarningsRecord, LeaderboardEntry } from './types';

export const mockNodes: Node[] = [
  {
    id: 'node-1',
    network_type: 'helium',
    lat: 37.7749,
    lng: -122.4194,
    status: 'active',
    last_seen: new Date().toISOString(),
    reward_rate_usd: 16.5,
    reliability_score: 98,
    total_verifications: 234,
    name: 'Downtown Hotspot',
  },
  {
    id: 'node-2',
    network_type: 'xnet',
    lat: 37.7849,
    lng: -122.4094,
    status: 'active',
    last_seen: new Date().toISOString(),
    reward_rate_usd: 12.3,
    reliability_score: 95,
    total_verifications: 189,
    name: 'Mission WiFi',
  },
  {
    id: 'node-3',
    network_type: 'helium',
    lat: 37.7649,
    lng: -122.4294,
    status: 'inactive',
    last_seen: new Date(Date.now() - 86400000).toISOString(),
    reward_rate_usd: 8.7,
    reliability_score: 72,
    total_verifications: 56,
    name: 'SOMA Node',
  },
  {
    id: 'node-4',
    network_type: 'geodnet',
    lat: 37.7949,
    lng: -122.3994,
    status: 'active',
    last_seen: new Date().toISOString(),
    reward_rate_usd: 23.4,
    reliability_score: 99,
    total_verifications: 412,
    name: 'Financial District',
  },
  {
    id: 'node-5',
    network_type: 'hivemapper',
    lat: 37.7549,
    lng: -122.4394,
    status: 'active',
    last_seen: new Date().toISOString(),
    reward_rate_usd: 19.8,
    reliability_score: 96,
    total_verifications: 301,
    name: 'Golden Gate Sensor',
  },
];

export const mockEarnings: EarningsRecord[] = [
  {
    node_id: 'node-1',
    network_type: 'helium',
    amount_usd: 16.5,
    amount_native_token: 0.0045,
    status: 'confirmed',
    reported_at: new Date().toISOString(),
    verified_at: new Date().toISOString(),
  },
  {
    node_id: 'node-2',
    network_type: 'xnet',
    amount_usd: 12.3,
    amount_native_token: 0.0032,
    status: 'confirmed',
    reported_at: new Date(Date.now() - 3600000).toISOString(),
    verified_at: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    node_id: 'node-4',
    network_type: 'geodnet',
    amount_usd: 23.4,
    amount_native_token: 0.0067,
    status: 'pending',
    reported_at: new Date(Date.now() - 7200000).toISOString(),
  },
];

export const mockLeaderboard: LeaderboardEntry[] = [
  {
    rank: 1,
    user_fid_anon: 'user_***234',
    total_earnings_30d: 1247.89,
    nodes_verified: 156,
    region: 'San Francisco',
  },
  {
    rank: 2,
    user_fid_anon: 'user_***891',
    total_earnings_30d: 1098.45,
    nodes_verified: 142,
    region: 'San Francisco',
  },
  {
    rank: 3,
    user_fid_anon: 'user_***567',
    total_earnings_30d: 987.23,
    nodes_verified: 128,
    region: 'San Francisco',
  },
  {
    rank: 4,
    user_fid_anon: 'You',
    total_earnings_30d: 856.12,
    nodes_verified: 98,
    region: 'San Francisco',
  },
];
